version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    container_name: cake-shop-api
    environment:
      - 'DB_ADDRESS=host.docker.internal:3306'
