CREATE TABLE IF NOT EXISTS cakes (
    id INT(10) NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL DEFAULT NULL,
    rating FLOAT NOT NULL DEFAULT 0,
    image VARCHAR(255) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);